### ISSUE TITLE
service bruteforce - doesn't work

### ISSUE THREAD

**Issue by 66Ton99** [cryptic-game/frontend#380]
**Describe the bug**
Can't hack any computer

**Reproduce**
Run any `service bruteforce  <target-device> <target-service>`

**Logs**
```
main.60a4daf92dc2b130.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'replace')
    at y (844.e45affaa61ddad59.js:1:3204)
    at g.promptAppender (844.e45affaa61ddad59.js:1:6732)
    at Object.next (844.e45affaa61ddad59.js:1:24600)
    at Ke.next (main.60a4daf92dc2b130.js:1:82034)
    at Ge._next (main.60a4daf92dc2b130.js:1:81712)
    at Ge.next (main.60a4daf92dc2b130.js:1:81401)
    at main.60a4daf92dc2b130.js:1:79393
    at oe (main.60a4daf92dc2b130.js:1:98002)
    at ue.next (main.60a4daf92dc2b130.js:1:79291)
    at Le.handleMessage (main.60a4daf92dc2b130.js:1:8492)
```

**Comment by 66Ton99** [comment]
It works now correctly

**Comment by 66Ton99** [comment]
It returns again
